scroll to reader marker
quotient-im/Quaternion pull request #729
Opened 2021-01-21 19:56 UTC by ddanilov

resolves #257

2021-01-22 13:57 UTC, KitsuneRal requested changes
Thanks for the PR! I was hoping someone would beat me to it :) Now the main problem with it is the amount of copy-pasted code. Can you please move the common part to a separate QML file and use it from `Timeline.qml` twice, configuring the component as necessary?

2021-01-22 13:57 UTC, KitsuneRal commented on client/qml/Timeline.qml
> +            name: "go-top"
What would be a fallback if the icon is not there?

2021-01-22 13:57 UTC, KitsuneRal commented on client/qml/Timeline.qml
> +        property bool v: messageModel.readMarkerVisualIndex > chatView.indexAt(chatView.contentX, chatView.contentY)
That's a good start but maybe it would also be great to have this button when the read marker is below? Might need to use a different icon for that case though.

2021-01-23 11:39 UTC, ddanilov commented on client/qml/Timeline.qml
> +            name: "go-top"
I will add one, based on scrolldown.svg

2021-01-23 11:46 UTC, ddanilov commented on client/qml/Timeline.qml
> +        property bool v: messageModel.readMarkerVisualIndex > chatView.indexAt(chatView.contentX, chatView.contentY)
maybe in a later change, as the first step I would like to keep in one direction only

2021-01-24 15:53 UTC, KitsuneRal commented on client/qml/ScrollToButton.qml
> +    anchors.bottomMargin: visible ? height / 2 : -height
Better define anchors directly in the instance - I don't think it can be defined as a "default" for _some_ scroll-to button.

2021-01-24 16:03 UTC, KitsuneRal requested changes
Thanks, that's better - but I'd prefer the two instances to be equal, not one enjoying default anchoring and signal handling, and the other overriding all that. `ScrollToButton` as an abstract class should be neutral.

2021-01-24 16:03 UTC, KitsuneRal commented on client/qml/ScrollToButton.qml
> +    }
Again, instance-specific behaviour. Ideally, define a custom `signal scrollRequested` or something, and do:
```suggestion
    onClicked: {
        scrollRequested()
        chatView.saveViewport()
    }
```
then implement `onScrollRequested` handler in each instance. Or just entirely define `onClicked` in each instance - that's simpler, even if duplicates the `saveViewport()` call.

2021-01-24 19:26 UTC, KitsuneRal approved these changes
Fabulous!

2021-01-24 19:26 UTC, merged