Systray improvements
quotient-im/Quaternion pull request #818
Opened 2022-01-29 17:56 UTC by Tamaranch

The first two commits are fixes for what I think are bugs.

The third commit is a minimal change to make the notification system usable in practice (from my point of view), once the two previous fixes are applied.

The fourth commit is an improvement proposal. I have been using the whole thing for a few days now locally.

I'm new to Qt, and my memories of C++ are old (I'm from the C/GTK side :slightly_smiling_face:), so I hope I didn't do too much stupid things or reinvent the wheel.

2022-01-29 19:23 UTC, CarlSchwan commented on client/systemtrayicon.cpp
> +    {
```suggestion
    if (m_notified && old == NULL && qApp->activeWindow() != nullptr) {
```

2022-01-29 19:23 UTC, CarlSchwan commented on client/systemtrayicon.cpp
> +        setToolTip("Quaternion");
```suggestion
        setToolTip(tr("Quaternion"));
```

2022-01-29 19:32 UTC, Tamaranch commented on client/systemtrayicon.cpp
> +        setToolTip("Quaternion");
There is already one occurrence above (in the constructor) that is not translated: should I add it to the translation too?

2022-01-30 13:53 UTC, CarlSchwan commented on client/systemtrayicon.cpp
> +        setToolTip("Quaternion");
Best to ask @kitsune :) Generally it's better to have every string in the user interface wrapped in i18n/tr called as some languages transliterate even the 'brand' names

2022-02-09 19:06 UTC, KitsuneRal commented on client/systemtrayicon.cpp
> +        setToolTip("Quaternion");
We don't translate Quaternion.

2022-02-09 19:35 UTC, KitsuneRal requested changes
There are a few things that could be better here and there but the main question I have for now is whether it's good to trigger on notifications instead of highlights. Given that the loudest ("intrusive") mode focuses the application, a series of notifications from messages in a 1:1 chat may be quite disruptive if they come, say, every minute or even more frequently. Perhaps it's worth handling notifications and highlights differently in that mode specifically. Also, as I wrote below, you seem to mis-accumulate the number of notifications across the application if that's what you tried to do.

2022-02-09 19:35 UTC, KitsuneRal commented on client/mainwindow.cpp
> +        systemTrayIcon->newRoom(r);
At this point `allRooms()` will always return an empty container because the first sync hasn't occurred yet; and during syncs, the tray is updated about new room objects via the `newRoom` signal - the respective `connect()` call is right below here.

2022-02-09 19:35 UTC, KitsuneRal commented on client/systemtrayicon.cpp
> +    if (qApp->activeWindow() != nullptr || room->notificationCount() == 0)
Highlights and notifications are not exactly the same thing in Matrix. It's a bit complex but basically highlights are supposed to be "louder" than notifications. E.g. a new message in a 1:1 chat normally causes a notification but not a highlight - for a highlight to be triggered, one has to be mentioned. I'm not quite sure if it's best to elevate notifications to system tray popups; but you might have a point.

2022-02-09 19:35 UTC, KitsuneRal commented on client/systemtrayicon.cpp
> +    for (auto* r: room->connection()->allRooms())
I'm not sure what you try to do here. The room's connection can be one of several currently active: if I'm logged in with two accounts in Matrix you'll only count notifications from one here. If you want to sum up all currently active notifications (potentially a big lot, unlike highlights - see my other comment) then you should traverse across all connections (stored in `AccountRegistry`).

2022-02-09 19:35 UTC, KitsuneRal commented on client/systemtrayicon.cpp
> +void SystemTrayIcon::focusChanged(QWidget* old, QWidget* now)
```suggestion
void SystemTrayIcon::focusChanged(QWidget* old)
```
A nice thing about Qt slots is that you don't need to fully match the signal parameters; unused parameters at the end can be dropped.

2022-02-09 19:35 UTC, KitsuneRal commented on client/systemtrayicon.h
> +        void focusChanged(QWidget* old, QWidget* now);
```suggestion
        void focusChanged(QWidget* old);
```

2022-02-10 16:29 UTC, Tamaranch commented on client/systemtrayicon.cpp
> +    for (auto* r: room->connection()->allRooms())
It should be good now.

2022-02-10 16:30 UTC, Tamaranch commented on client/mainwindow.cpp
> +        systemTrayIcon->newRoom(r);
That's not what I'm seeing: this change does get me into `systemTrayIcon::newRoom()` at startup (so the container doesn't seem empty), and that's necessary so that I'm notified of unread messages from the previous session.

2022-02-10 16:30 UTC, Tamaranch commented on client/systemtrayicon.cpp
> +    if (qApp->activeWindow() != nullptr || room->notificationCount() == 0)
Oh ok, I see. I seem to have a somewhat peculiar and minimalist use of the software, actually: maintaining a single IRC connection via Matrix on a few fairly low-traffic channels, where I'm almost never mentioned, hence my impression that the notifications weren't working.

So it may be that the current state of the notification system suits the majority of users, and that this PR is not very relevant. I will continue to use this patch for me, as it is suitable for my case, but maybe it is better to just close this PR?

2022-12-21 17:34 UTC, KitsuneRal commented on client/mainwindow.cpp
> +        systemTrayIcon->newRoom(r);
Hm, interesting, maybe I misunderstand something in the way things work now...

2022-12-21 17:42 UTC, KitsuneRal commented on client/systemtrayicon.cpp
> +    if (qApp->activeWindow() != nullptr || room->notificationCount() == 0)
You might want to login to Matrix from another client (Element Web, e.g.) once, and tune notifications for those rooms (or even for the whole account) so that all notifications are "loud" (the rightmost setting in respective lines). As for this PR, I think at least some pieces of it are still worthwhile - I really like the icon change, in particular - so perhaps I'll cherry-pick those.

2025-03-12 17:39 UTC, merged

2025-03-12 17:39 UTC, KitsuneRal commented
Based on your code I made 584425359082d6bcbe00ec3ee2aa5f0222252f01, and your commits are in the merged trail - thanks a lot for the contribution!