Chatedit: make default pasting behavior configurable
quotient-im/Quaternion pull request #854
Opened 2023-02-17 10:45 UTC by rpallai

Many people like pasting plain text as there is less trouble with it and does the job. Even Element pastes plain text by default despite of being a rich client. This is why this patch switches to plain text pasting by default while makes it configurable.

Other version can be pasted by `Ctrl+Shift+V`.

Cc #730

2023-02-20 14:54 UTC, berrange commented
While this looks like as a usable workaround, I still feel like the current paste-as-HTML impl is fundamentally broken in its implementation. If it can't reliably paste in HTML that has been selected in the browser window, it does not look fit for purpose as is. Pasting 100% complete well formed HTML documents does not look likely to be the common case.

2023-02-27 11:02 UTC, KitsuneRal requested changes
Thanks - overall LGTM, save for one fix.

2023-02-27 11:02 UTC, KitsuneRal commented on client/chatedit.cpp
> +                                                      : "Paste as plain text"),
I don't think this works with Qt Linguist - it needs both strings to be there in separate, so that they land in separate translation slots.
```suggestion
                         pastePlaintextByDefault() ? tr("Paste as rich text")
                                                   : tr("Paste as plain text"),
```

2023-02-27 12:14 UTC, KitsuneRal approved these changes

2023-02-27 12:59 UTC, merged